version: '3.2'
services:
  redis:
    image: redis
  app:
    build:
      context: .
      args:
        - "BUNDLE_GITHUB__COM=$PRONTO_GITHUB_ACCESS_TOKEN"
    volumes:
      - ./artifacts:/usr/src/app/artifacts
    links:
      - redis
    depends_on:
      - redis
    environment:
      # buildkite
      CI:
      BUILDKITE_PARALLEL_JOB:
      BUILDKITE_PARALLEL_JOB_COUNT:
      BUILDKITE_COMMIT:
      BUILDKITE_BRANCH:
      BUILDKITE_REPO:
      BUILDKITE_BUILD_ID:
      BUILDKITE_BUILD_NUMBER:
      REDIS_URL: 'redis://redis:6379/11'