steps:
  - label: ":rubocop: Rubocop"
    command:
      - "./bin/ci/rubocop"
    artifact_paths: "artifacts/*"
    plugins:
      returnly/aws-ssm#v1.0.0:
      docker-compose:
        config: "docker-compose.tests.yml"
        run: "app"
    soft_fail:
      - exit_status: 1
    agents:
      queue: "ruby-tests"

  - label: "RSpec"
    artifact_paths: "artifacts/*"
    plugins:
      returnly/aws-ssm#v1.0.0:
      docker-compose#v3.0.2:
        config: "docker-compose.tests.yml"
        propagate-environment: true
        mount-buildkite-agent: true
        volumes:
          - ${BUILDKITE_AGENT_BINARY_PATH:-/usr/bin/buildkite-agent}:/usr/bin/buildkite-agent
        environment:
          - BUILDKITE
          - BUILDKITE_BUILD_ID
          - BUILDKITE_JOB_ID
          - BUILDKITE_AGENT_ACCESS_TOKEN
        run: "app"
    timeout_in_minutes: 10
    agents:
      queue: "ruby-tests"

  - wait: ~
    continue_on_failure: true

  - label: ":pencil: Annotate linting results"
    plugins:
      - bugcrowd/test-summary#v1.11.0:
          inputs:
            - label: ":rubocop: Rubocop"
              artifact_path: artifacts/rubocop.tabs
              type: oneline
            - label: ":brakeman: Brakeman"
              artifact_path: artifacts/brakeman.tabs
              type: oneline
          formatter:
            type: details
          context: failures