#!/bin/bash

set -euo pipefail

SHORT_COMMIT_HASH="$(git rev-parse --short=8 HEAD)"

if [ $BUILDKITE_BRANCH = 'master' ]; then
    BRANCH_TAG_PREFIX='master'
else
    BRANCH_TAG_PREFIX='branch'
fi

RETURNLY_DOCKER_TAG="$BRANCH_TAG_PREFIX-$SHORT_COMMIT_HASH"

export SHORT_COMMIT_HASH
export BRANCH_TAG_PREFIX
export RETURNLY_DOCKER_TAG
